### PR TITLE
Add option for 'sr_lastupdate_offset' and also use it

### PR DESCRIPTION
**Pull request by WillPresley**
I got sick of trying to get multiple vendors to wrangle timezones and UTC correctly, so I instead implemented this simple option to manually adjust the '{lastUpdate}' variable using PHP date/time strings. Please feel free to give any tips on code style, tests, etc and I can make the changes.

I whipped this up fairly quickly due to a client's needs, so it probably needs some more eyes on it. May also try to take a look at #212 but other projects are already pulling me away at the moment.

### CODE REVIEW

**Comment by CodyReichert** [comment]
Hey @WillPresley - this is great, thank you for the PR! We should be able to pull this is no problem, let me just test a bit locally.

One thing is that, there will be a conflict with the fix we have for #212. I may just cherry pick your commit here into my PR and resolve it on my end, but I'll make sure you get author credit for the commit.

I will keep you posted!

**Comment by WillPresley** [comment]
> Hey @WillPresley - this is great, thank you for the PR! We should be able to pull this is no problem, let me just test a bit locally.
> 
> One thing is that, there will be a conflict with the fix we have for #212. I may just cherry pick your commit here into my PR and resolve it on my end, but I'll make sure you get author credit for the commit.
> 
> I will keep you posted!

Sounds good to me! I kind of thought that it may overlap with whatever was being done about #212, so cherry-picking makes sense to me.

**Comment by WillPresley** [comment]
Hey @CodyReichert cheers on the new version that fixes #212, I was going to check it out to confirm it is working, but I was going to check on this PR first. I don't really want to overwrite the plugin with the new version from the WP repo without being able to apply this fix for my client(s). Should I rebase off of 2.9.11 and update here?

**Comment by CodyReichert** [comment]
Hey @WillPresley -- sorry for the delay on this! We've been talking about it internally a bit.

I pushed an alternative solution I wanted to get your thoughts on. Check out #234.

This uses JS to localize the timestamp automatically to the browser's timezone. I believe that is the over-arching issue you were looking to fix. Does that look like it will work well for you?

(I can post a .zip file for the plugin if you want to test it!)

**Comment by WillPresley** [comment]
@WillPresley The solution in #234 looks great and works well for me!

**Comment by CodyReichert** [comment]
Thanks for testing it @WillPresley! We really appreicate the contribution!

I'll go ahead and close this PR, but please do feel free to open another one if you have any ideas or improvements (or an issue is great, too).

**Pull request closed without merging**
